version: "3.8"

services:
  web_backend:
    image: web_backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      - REDIS_HOST=redis
    ports:
      - 8080:8080
    volumes:
      - ./example-backend:/usr/src/app/example-backend
    container_name: web_backend
  web_frontend:
    image: web_frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./example-frontend:/usr/src/app/example-frontend
    container_name: web_frontend
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
    command: ["redis-server"]
    container_name: redis
