version: "3.8"

services:
  web_backend:
    image: web_backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - 8080:8080
    volumes:
      - ./example-backend:/usr/src/app/example-backend
    container_name: web_backend
  web_frontend:
    image: web_frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./example-frontend:/usr/src/app/example-frontend
    container_name: web_frontend
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
    command: ["redis-server"]
    container_name: redis
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: postgres
  nginx:
    image: nginx:1.20.1
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy
