version: "3.8"

services:
  ml-frontend:
    image: ml-frontend
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000
    container_name: ml-frontend

  ml-backend:
    image: ml-backend
    build: ./ml-kurkkumopo-backend

    ports:
      - 5000:5000
    volumes:
      - model:/src/model
    container_name: ml_backend

  ml-training:
    image: ml-training
    build: ./ml-kurkkumopo-training
    volumes:
      - model:/src/model
      - imgs:/src/imgs
    container_name: ml-training

volumes:
  model:
  imgs:
